### ISSUE TITLE
Create project structure

### ISSUE THREAD

**Issue by przemgk** [przemgk/frontend-mentor-ch17#1]
**Tasks to do:**
- [x] Install React and configure tools
- [x] Make decision about project stucture (create folders)
- [x] Add site on netlify
