### ISSUE TITLE
Add animations and styles for mobile

### ISSUE THREAD

**Issue by przemgk** [przemgk/frontend-mentor-ch17#4]
**Tasks to do:**
- [x] Open modal animation
- [x] Button hover states
- [x] Add mobile styles
